In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
plt.style.use('ggplot')
%matplotlib inline
import seaborn as sns

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

## Gondar

In [118]:
file_path = "/Users/gemavidal/Box Sync/Vet/Projects and Papers/2020 Ethiopia Pathasure/Gondar Data Analyses/df_trusted_Y1Y2.csv"
df_gondar = pd.read_csv(file_path, index_col = False)

In [119]:
df_colostrum_gondar = df_gondar[['district', 
                                 'dam_ageparturition', 'dam_bcs1to5', 'parity',
                                 'age', 'age_units', 'sex', 'timeofbirth',
                                 'colostrumwithin24hours', 'reasonnocolostrumfedwithin24hours',
                                 'colostrumfeeding', 'colostrumfromstepmom',
                                 'continuousaccesstodamfirst24hours',
                                 'timetofirstcolostrum_hrs_Chalachew', 'timetofirstcololstrum_hrs_Nuru']]

In [120]:
df_colostrum_gondar = df_colostrum_gondar.rename(columns = {'dam_ageparturition':'dam_ageparturition_years',
                                                            'timetofirstcololstrum_hrs_Nuru':'timeto_firstcolostrum'})

## Sululta

In [121]:
file_path = "/Users/gemavidal/Box Sync/Young Stock Mortality/Publications in Process/Cleaned Datasets/df_Sululta_PhysEnrollLab_Y2 copy.csv"
df_sululta = pd.read_csv(file_path, index_col = False)

df_sululta_i = df_sululta.loc[(df_sululta['in_classmate'] != 'unknown')]

In [122]:
df_colostrum_sululta = df_sululta_i[['district', 
                                     'dam_ageparturition_years', 'dam_bcs1to5', 'parity',
                                     'age_month', 'age_units',
                                     'sex', 'timeofbirth',
                                     'colostrumwithin24hours', 'reasonnocolostrumfedwithin24hours',
                                     'continuousaccesstodamfirst24hours',
                                     'timeofcolostrumsucking']]

In [123]:
df_colostrum_sululta = df_colostrum_sululta.rename(columns = {'age_month':'age'})

In [124]:
def timeof_colostrum_sululta (row):
    if (row['timeofcolostrumsucking'] == '30min'):
        return 'Before an hour'
    if (row['timeofcolostrumsucking'] == '1hr'):
        return 'Before an hour'
    if (row['timeofcolostrumsucking'] == '2hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking'] == '3hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking'] == '4hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking'] == '6hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking'] == '7hr'):
        return '7-12 hours'

In [125]:
df_colostrum_sululta['timeto_firstcolostrum'] = df_colostrum_sululta.apply(lambda row: timeof_colostrum_sululta(row), axis = 1)

## Dalocha

In [126]:
file_path = "/Users/gemavidal/Box Sync/Young Stock Mortality/Publications in Process/Cleaned Datasets/df_Dalocha_PhysEnrollLab_Y2 copy.csv"
df_dalocha = pd.read_csv(file_path, index_col = False)

df_dalocha_i = df_dalocha.loc[(df_dalocha['trusted'] == 'yes')]

In [127]:
df_colostrum_dalocha = df_dalocha_i[['district', 
                                     'dam_ageparturition_years', 'dam_bcs1to5', 'parity',
                                     'age', 'age_units',
                                     'sex', 'timeofbirth',
                                     'colostrumwithin24hours', 'colostrumwithin24hours_whynot',
                                     'continuousaccesstodamfirst24hours']]

In [128]:
df_colostrum_dalocha = df_colostrum_dalocha.rename(columns = {'colostrumwithin24hours_whynot':'reasonnocolostrumfedwithin24hours'})

## Awash-Fentale

In [129]:
file_path = "/Users/gemavidal/Box Sync/Young Stock Mortality/Publications in Process/Cleaned Datasets/df_Awash_PhyEnrollLab_Y2.csv"
df_awash = pd.read_csv(file_path, index_col = False)

In [130]:
for i in df_awash:
    print (df_awash[i].value_counts())

AF077078079_090091092_Y2        22
AF056a_064_061_73_066_078_Y2    17
AF057_066_Y2                    11
AF014_060_070_Y2                11
AF011_058_067_Y2                11
HHLGK10012                      10
AF005_046_Y2                    10
AF070_082_075_088_Y2             9
AF013_Y2                         9
HHLGK3004                        9
HHLGK005                         9
AF023_Y2                         9
AF010_Y2                         9
AF060a_071_Y2                    8
AF002_Y2                         8
AF044_Y2                         8
AF048_068_Y2                     8
HHLGK12016                       7
AF034_Y2                         7
HHLGK13021                       7
HHGK004                          6
HHLGK001                         6
HHLGK008                         6
AF062_074_Y2                     6
AF045_Y2                         6
HHLGK9011                        5
AF007_053_062_Y2                 5
AF060b_072_Y2                    5
HHL002                           5
AF040_Y2                         5
                                ..
AF003_Y2                         2
AF004_Y2                         2
AF029_Y2                         2
AF032_Y2                         2
AF039_Y2                         2
HHGK011                          2
HHL026                           2
AF051_059_069a_Y2                2
AF021_Y2                         1
AF086_Y2                         1
AF074_087_Y2                     1
AF033_Y2                         1
AF030_Y2                         1
AF042_Y2                         1
AF031_Y2                         1
AF067_079_Y2                     1
AF063_075_Y2                     1
AF038_Y2                         1
AF083_Y2                         1
AF019_Y2                         1
AF020_Y2                         1
HHL003                           1
AF025_Y2                         1
AF027_Y2                         1
AF049_069_Y2                     1
AF080_Y2                         1
AF058a_068a_Y2                   1
AF028_Y2                         1
HHGK015                          1
AF043_Y2                         1
Name: New_HH_ID, Length: 107, dtype: int64
AFY2C356    1
AFY2C180    1
AFY2C341    1
AFY2C210    1
AFY2C211    1
AFY2C212    1
AFY2C213    1
AFY2C214    1
AFY2C215    1
AFY2C348    1
AFY2C349    1
AFY2C188    1
AFY2C189    1
AFY2C181    1
AFY2C343    1
AFY2C182    1
AFY2C183    1
AFY2C184    1
AFY2C185    1
AFY2C186    1
AFY2C187    1
AFY2C358    1
AFY2C401    1
AFY2C269    1
AFY2C268    1
AFY2C265    1
AFY2C340    1
AFY2C342    1
AFY2C030    1
AFY2C164    1
           ..
AFY2C371    1
AFY2C370    1
AFY2C082    1
AFY2C083    1
AFY2C080    1
AFY2C081    1
AFY2C395    1
AFY2C394    1
AFY2C397    1
AFY2C071    1
AFY2C391    1
AFY2C390    1
AFY2C018    1
AFY2C019    1
AFY2C431    1
AFY2C430    1
AFY2C437    1
AFY2C436    1
AFY2C302    1
AFY2C303    1
AFY2C300    1
AFY2C301    1
AFY2C306    1
AFY2C307    1
AFY2C304    1
AFY2C305    1
AFY2C417    1
AFY2C308    1
AFY2C309    1
AFY2C221    1
Name: New_Case_ID, Length: 441, dtype: int64
Seid Asbo                22
Adem Ali                 17
Hasen Goda               11
Hawa Ahmed_Esa Selila    11
Seid Bolele              11
Abubeker Mehamed         10
Musa Mehamed              9
Ude Ahado                 9
Humed Gebaba              9
Dini Ebrahim              9
Ali Musa                  8
Nura Ebrahem              8
Ahmed Hegen               8
Abdo Mehamed              8
Kulo Ujlo                 7
Hassen Ali                6
Ahmed Addes               6
sra Gure                  5
Ahmed Nuri                5
Ahmed Geneto              5
Mehamed Hassen            5
Akle Seid                 5
Ergedo Hasen              5
Hasen Mehamed             5
Mehamed Husen             4
Abubeker Hamede           4
Ali Hasen                 4
Ali Gale                  4
Musa Debay                4
Esa  Yesuf                4
                         ..
Esa Dego                  2
Adu Gebaba                2
Ebrahim Hasen             2
Ahmed Ali                 2
Jibril Hasen              2
sra Mehamed               2
Ahmed Belea               2
Moyele Ali                2
Haji Husen                2
Fatuma Nuri               2
Husen Ugayle              2
Bidaro Hotale             1
Beale Seule               1
Humed Hate                1
Mehamed Mustefa           1
Dula Elenza               1
Ali Umer                  1
Ahmed Akle                1
Edun Mehamed              1
Sekle Seid                1
Jilo Mehamed              1
Mehamed Nehiba            1
Dugoda Daie               1
Humed Habule              1
Fatuma Mehamed            1
As Bila                   1
Bulo Hasen                1
Abasaile Mehamed          1
Seid Hasen                1
Adem Muhamed              1
Name: Livestock_Owner, Length: 72, dtype: int64
Negash             141
Erd_Hab            130
Erdachew            84
Erd_Hab_Addisu      69
Erdachew_Addisu     17
Name: student, dtype: int64
Awash      287
Amibara    154
Name: district, dtype: int64
Bovine      300
lamb         97
goat kid     44
Name: Species, dtype: int64
serum    141
Name: Specimen_type_Negash, dtype: int64
serum    86
Name: Specimen_type_Addisu, dtype: int64
feces    199
Name: Specimen_type_Hab, dtype: int64
ear notch    300
Name: Specimen_type_Erd, dtype: int64
Path_Salmonella    199
Name: Test_Hab, dtype: int64
BVD Ag    300
Name: Test_Erd, dtype: int64
RID    141
Name: Test_Negash, dtype: int64
2177.285    5
4926.463    4
995.332     4
1831.702    4
2540.293    4
1199.827    3
1944.960    3
831.052     3
623.612     3
805.600     3
2920.725    3
3733.862    3
3184.027    3
2060.155    3
899.498     2
2902.568    2
2417.354    2
1503.543    2
1720.379    2
47.640      2
2383.550    2
5902.228    2
2665.168    2
3271.343    2
1610.993    2
713.638     2
4616.697    2
3051.408    2
4020.396    2
1265.273    2
           ..
5243.974    1
3593.499    1
2725.009    1
1982.336    1
5405.634    1
5084.251    1
535.522     1
169.577     1
1331.858    1
1755.266    1
5569.229    1
662.030     1
307.482     1
2813.219    1
2791.978    1
2993.054    1
1093.102    1
1829.818    1
4464.718    1
3177.442    1
2060.303    1
3084.679    1
2467.208    1
1468.441    1
6071.632    1
503.251     1
2665.163    1
2301.031    1
5737.761    1
3876.161    1
Name: IgG_Negash, Length: 67, dtype: int64
RID    86
Name: Test_Addisu, dtype: int64
1966.026    7
2585.726    7
2513.572    7
1837.386    6
NR          6
2732.507    4
2958.865    4
1774.303    3
2807.135    3
1712.044    3
1650.61     3
2165.171    3
1590.001    3
1471.256    2
732.4       2
1901.294    2
2031.583    2
1243.662    2
2587.726    2
2097.965    1
1966.062    1
2371.738    1
2882.588    1
382.763     1
2442.242    1
1355.81     1
227.735     1
2302.058    1
1029.262    1
2658.704    1
2233.202    1
1530.216    1
Name: IgG_Addisu, dtype: int64
adequate    64
partial     10
failure      4
Name: IgG_Status, dtype: int64
D1       1
E9       1
P2H12    1
P3B9     1
P3B8     1
P3C10    1
P2G1     1
P3C11    1
P7F11    1
P3B6     1
P7F10    1
P7F12    1
P2B8     1
P2B9     1
P7E12    1
E8       1
P2B11    1
P2H11    1
P7E11    1
P2E2     1
P2E4     1
P2E7     1
P2E6     1
B8       1
B9       1
P2E3     1
A3       1
P2F7     1
P2H6     1
P7H12    1
        ..
F7       1
P2A9     1
P2A8     1
P2H7     1
P2A3     1
P6H8     1
P6H9     1
P3A7     1
A10      1
P7F9     1
P7F8     1
F3       1
F1       1
P7G2     1
P7G5     1
P7G3     1
P2B10    1
P7G1     1
P7G6     1
P7G7     1
P7G4     1
P7G8     1
P2E12    1
P7G9     1
P3D4     1
G2       1
P2E11    1
P2E10    1
P2D3     1
P2F10    1
Name: BVD_Plate, Length: 287, dtype: int64
0.1295    4
0.1194    3
0.1293    2
0.1379    2
0.1471    2
0.1310    2
0.1213    2
0.1157    2
0.1144    2
0.1100    2
0.1207    2
0.1159    2
0.1490    2
0.1405    2
0.1298    2
0.1273    2
0.1299    2
0.1186    2
0.1246    2
0.1219    2
0.1543    2
0.1259    2
0.1368    2
0.1066    2
0.1183    2
0.1110    2
0.1296    2
0.1221    2
0.1499    2
0.1291    2
         ..
0.1018    1
0.1093    1
0.1501    1
0.1602    1
0.1282    1
0.2004    1
0.2341    1
0.1161    1
0.1343    1
0.1375    1
0.1297    1
0.1149    1
0.1230    1
0.1073    1
0.1409    1
0.1234    1
0.3212    1
0.1276    1
0.1750    1
0.1000    1
0.1731    1
0.1707    1
0.1318    1
0.1503    1
0.1281    1
0.1152    1
0.1522    1
0.1754    1
0.1423    1
0.1269    1
Name: BVD_OD, Length: 249, dtype: int64
NEGATIVE    289
Name: BVD_Result, dtype: int64
NEGATIVE    155
POSITIVE     44
Name: ecoli_result, dtype: int64
NEGATIVE    171
POSITIVE     28
Name: rota_result, dtype: int64
NEGATIVE    167
POSITIVE     32
Name: coro_result, dtype: int64
NEGATIVE    125
POSITIVE     74
Name: crypto_result, dtype: int64
NEGATIVE    189
POSITIVE     10
Name: salmonella_enterica_result, dtype: int64
Bright/Alert    359
Depressed        53
Lethargic        16
Comatose          2
Name: attitude, dtype: int64
no                                  141
emaciated and dry mucus membrane      1
abnormal gait                         1
emaciated                             1
Uble to suckle                        1
Name: generalnotes, dtype: int64
39.6      23
39.1      16
38.1      15
38.6      14
37.9      14
38.7      13
38.9      13
38.3      12
39.4      11
39.9      10
38.2      10
37.8      10
39.3      10
38.8       9
38.0       9
37.6       8
39.2       8
38.4       7
38.5       7
39.0       6
37.3       4
36.8       4
39.8       4
39.7       4
37.1       4
39.5       3
36.0       3
36.5       3
36.9       3
40.1       3
36.2       2
36.4       2
37.2       2
35.9       2
37.7       2
36.6       2
36.7       2
37.4       1
3838.0     1
34.6       1
35.7       1
41.0       1
35.5       1
37.5       1
35.4       1
35.6       1
42.3       1
369.1      1
36.3       1
Name: rectal_temp, dtype: int64
0.0    106
3.0     71
1.0     68
2.0     41
Name: rectal_temp_score, dtype: int64
0    427
1      8
2      5
3      1
Name: cough_score, dtype: int64
0    394
1     30
2     16
3      1
Name: nasaldischarge_score, dtype: int64
0    421
2     10
1     10
Name: eye_score, dtype: int64
0    437
2      2
1      2
Name: ear_score, dtype: int64
0    438
1      3
Name: increased_respiratoryeffort, dtype: int64
32.0    74
28.0    57
36.0    28
24.0    18
34.0    15
18.0    14
22.0     9
38.0     9
40.0     8
26.0     8
30.0     7
20.0     5
42.0     4
16.0     4
44.0     3
46.0     3
14.0     3
12.0     2
60.0     1
48.0     1
35.0     1
31.0     1
Name: respiratory_rate_perminute, dtype: int64
no     184
yes     19
Name: wheezes, dtype: int64
no     194
yes      9
Name: crackles, dtype: int64
no    203
Name: lungsounds_muffled, dtype: int64
no     191
yes     12
Name: coughing, dtype: int64
78.0     26
82.0     24
72.0     20
80.0     20
60.0     19
52.0     19
56.0     19
84.0     18
88.0     18
64.0     13
76.0     13
68.0     11
74.0     10
92.0      9
70.0      9
86.0      8
94.0      5
96.0      3
73.0      2
90.0      2
100.0     1
58.0      1
66.0      1
62.0      1
48.0      1
98.0      1
87.0      1
Name: heart_rate_perminute, dtype: int64
no    203
Name: heart_abnormalsounds, dtype: int64
no    141
Name: thoracicauscultation_notes, dtype: int64
no    141
Name: ruminalcontractions_perminute, dtype: int64
no    141
Name: peristalticsounds_increased, dtype: int64
no    141
Name: abdomen_pingsounds, dtype: int64
no    141
        1
Name: abdomenauscultation_notes, dtype: int64
3.0    235
2.0     92
4.0     70
1.0     41
5.0      1
Name: BCS, dtype: int64
Normal      139
normal      136
abnormal      3
Abnormal      2
Name: navel, dtype: int64
no                       138
Mild infection             2
Infection on umblicus      1
Name: navelexam_notes, dtype: int64
Normal     300
normal     141
Name: jointsexam, dtype: int64
no    141
Name: jointsexam_notes, dtype: int64
0    387
2     41
1      7
3      6
Name: fecal_score, dtype: int64
no     429
yes      6
Name: feces_blood, dtype: int64
no                             141
mucus on faeces                  3
mucus on feaces                  2
smile                            1
mucus with faeces                1
diarric                          1
watery diarrhea                  1
straining during defication      1
whitish pasty faeces             1
Name: typeofdiarrhea, dtype: int64
1hr      46
2hr      24
5hr       6
3hr       5
6hr       2
3min      1
30min     1
7hr       1
Name: timeofcolostrumsucking_Addisu, dtype: int64
1.0    77
2.0     9
Name: timeofcolostrum_catg_Addisu, dtype: int64
7.0     72
1.0     69
3.0     67
2.0     57
4.0     47
5.0     46
6.0     29
15.0    14
20.0     9
1.5      8
21.0     6
14.0     5
8.0      5
3.5      1
10.0     1
28.0     1
0.5      1
16.0     1
9.0      1
Name: age, dtype: int64
days      248
months    183
weeks      10
Name: age_units, dtype: int64
1.00    48
2.00    36
3.00    27
4.00    19
0.23    16
0.50    14
0.10    13
5.00    11
6.00    11
0.13    10
0.67     9
0.03     8
1.50     7
0.70     7
0.07     6
0.20     6
0.17     5
8.00     4
7.00     4
0.47     4
3.50     1
0.27     1
0.93     1
0.53     1
Name: Age_month, dtype: int64
Female    209
Male      138
Male       83
male        1
female      1
Name: sex, dtype: int64
Local                 400
Improved/Crossbred     40
Name: breed, dtype: int64
Afar    423
Name: breed_me, dtype: int64
Live Cover    298
live cover    140
Live cover      1
live Cover      1
Name: sire, dtype: int64
Day        131
Night       98
Night       49
unknown     19
Name: timeofbirth, dtype: int64
yes        161
no          73
Yes         50
unknown     11
Name: birth_witness, dtype: int64
In barn    120
outside     73
in barn     65
unknown     19
Outside     18
Name: birthlocation, dtype: int64
normal      209
Normal       74
assisted     57
unknown      21
Assisted      8
Name: typedelivery, dtype: int64
yes        366
unknown      2
Name: colostrumwithin24hours, dtype: int64
0.0    74
1.0    67
Name: reasonnocolostrumfedwithin24hours, dtype: int64
no    366
Name: veldesinfection, dtype: int64
yes    310
Yes     54
no       4
Name: continuousaccesstodamfirst24hours, dtype: int64
yes    437
no       3
Name: housingseparatefromherd, dtype: int64
no     436
yes      4
Name: calfhousedwithdam, dtype: int64
yes    355
no      85
Name: calfhousewithotherlivestock, dtype: int64

no    440
Name: vaccitionssincebirth, dtype: int64
Series([], Name: typeofvaccinesreceived, dtype: int64)
no     427
yes     13
Name: medicationsincebirth, dtype: int64
no     299
yes     15
Name: medicationsincebirth_dewormer, dtype: int64
no    299
Name: medicationsincebirth_vitamins, dtype: int64
no    299
Name: medicationsincebirth_oralelectrolytes, dtype: int64
Series([], Name: medicationsincebirth_other, dtype: int64)
no     407
yes     33
Name: signsofillness_sincebirth, dtype: int64
no     373
yes     34
Name: signsofillness_saldischarge, dtype: int64
no     388
yes     11
Name: signsofillness_cough, dtype: int64
no     393
yes      2
Name: signsofillness_difficultybreathing, dtype: int64
no     388
yes     14
Name: signsofillness_oculardischarge, dtype: int64
no     391
yes      4
Name: signsofillness_cloudyeyes, dtype: int64
no     394
yes      1
Name: signsofillness_headtilt, dtype: int64
no    395
Name: signsofillness_circling, dtype: int64
no     385
yes     11
Name: signsofillness_notsuckling, dtype: int64
no     365
yes     50
 no      1
Name: signsofillness_diarrhea_notbloody, dtype: int64
no     393
yes      2
Name: Diarrhea (bloody), dtype: int64
no    395
Name: signsofillness_bloat, dtype: int64
no    395
Name: signsofillness_lameness, dtype: int64
no     393
yes      2
Name: signsofillness_swollenjoints, dtype: int64
no     392
yes      6
Name: signsofillness_velinfection, dtype: int64
no    395
Name: signsofillness_difficulturition, dtype: int64
no     393
yes      2
Name: signsofillness_straindefecate, dtype: int64
no    395
Name: signsofillness_birthdefects, dtype: int64
no    395
Name: signsofillness_collapse, dtype: int64
no    395
Name: signsofillness_predation, dtype: int64
no    395
Name: signsofillness_trauma, dtype: int64
no    395
Name: signsofillness_bleedingorifices, dtype: int64
no                       388
yes, depression            2
depresion, emaciation      1
Name: signsofillness_other, dtype: int64
no    440
Name: proceduredone_castratration, dtype: int64
no    440
Name: proceduredone_dehorning, dtype: int64
no    440
Name: proceduredone_branding, dtype: int64
no    440
Name: proceduredone_earnotch, dtype: int64
no    358
Name: proceduredone_taildocking, dtype: int64
yes milk    440
Name: feedmilkormilkreplacer, dtype: int64
twice a day              358
more than twice a day     82
Name: feedingfrequency, dtype: int64
unknown    399
0.5         31
0.4          5
0.75         2
5            1
0.55         1
0.2          1
Name: feedmilkormilkreplacer_liters, dtype: int64
no     438
yes      2
Name: supplementalfeed, dtype: int64
twice a day    1
unknown        1
Name: supplementalfeed_frequency, dtype: int64
no     235
yes     51
Name: watergiven, dtype: int64
once a day               29
twice a day              20
more than twice a day     2
Name: watergiven_frequency, dtype: int64
yes    97
no     60
Name: watergiven_independentwatertrough, dtype: int64
no    440
Name: weaned, dtype: int64
Series([], Name: weaned_agemonths, dtype: int64)
no    440
Name: bedding, dtype: int64
yes    292
no     148
Name: bedding_dryandclean, dtype: int64
yes    391
no      49
Name: calfgrouphousing_enoughspace, dtype: int64
5          84
4          77
7          63
8          51
6          37
9          30
10         29
3          26
12          9
11          4
13          4
15          4
14          3
3.5         3
unknown     3
2.5         2
2.7         1
2.9         1
2.8         1
16          1
9.5         1
4.8         1
2           1
5.5         1
Name: dam_ageparturition, dtype: int64
2          95
1          91
3          81
4          59
5          36
6          29
9          12
7           9
8           8
unknown     6
10          6
11          2
14          1
15          1
12          1
Name: parity, dtype: int64
no         225
unknown     97
Name: dam_vaccines2monthsbeforedelivery, dtype: int64
pasterullosis    1
Name: dam_vaccines_type, dtype: int64
yes        322
no           3
unknown      1
Name: dam_alive, dtype: int64
3          309
2           51
4           45
1           22
unknown      3
unkown       2
5            1
Name: dam_bcs1to5, dtype: int64
unknown              112
1                     70
2                     65
0.5                   50
1.5                   30
3                     24
0.75                  23
0 (only for calf)     11
5                      9
0.25                   6
7                      4
4                      4
3.5                    3
9                      3
6                      3
2.5                    3
0.1                    2
0                      2
11                     1
0.7                    1
10                     1
0.2                    1
0.3                    1
16                     1
14                     1
1.75                   1
12                     1
Name: dam_milkyield_liters, dtype: int64
yes        408
no          19
poor         4
unknown      1
Name: dam_motheringinstinct, dtype: int64
no    1
Name: dam_deathwithin2weeksparturition, dtype: int64
8 up to 10hrs    64
Name: weaned_grazinghours_rainyseason_Q48, dtype: int64
2 times per day    64
Name: weaned_accesstowater_hours_rainyseason_Q55, dtype: int64
10 up to 12 hrs    64
Name: weaned_grazinghours_dryseason_Q56, dtype: int64
2 times per day    64
Name: weaned_accesstowater_hours_dryseason_Q63, dtype: int64

In [131]:
df_colostrum_awash = df_awash[['district', 'dam_ageparturition', 'dam_bcs1to5', 'parity',
                               'age', 'age_units', 'Species',
                               'sex', 'timeofbirth', 'timeofcolostrumsucking_Addisu',
                               'colostrumwithin24hours', 'reasonnocolostrumfedwithin24hours',
                               'continuousaccesstodamfirst24hours']]

In [132]:
df_colostrum_awash = df_colostrum_awash.rename(columns = {'dam_ageparturition':'dam_ageparturition_years'})

In [133]:
def timeof_colostrum_awash (row):
    if (row['timeofcolostrumsucking_Addisu'] == '3min'):
        return 'Before an hour'
    if (row['timeofcolostrumsucking_Addisu'] == '30min'):
        return 'Before an hour'
    if (row['timeofcolostrumsucking_Addisu'] == '1hr'):
        return 'Before an hour'
    if (row['timeofcolostrumsucking_Addisu'] == '2hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking_Addisu'] == '3hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking_Addisu'] == '5hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking_Addisu'] == '6hr'):
        return '2-6 hours'
    if (row['timeofcolostrumsucking_Addisu'] == '7hr'):
        return '7-12 hours'

In [134]:
df_colostrum_awash['timeto_firstcolostrum'] = df_colostrum_awash.apply(lambda row: timeof_colostrum_awash(row), axis = 1)

## Combine DataFrames

In [135]:
dfs = [df_colostrum_gondar, df_colostrum_sululta, df_colostrum_dalocha, df_colostrum_awash]

for i in dfs:
    print i.shape

(564, 15)
(117, 13)
(358, 11)
(441, 14)

In [136]:
df_colostrum = pd.DataFrame([])

for i in dfs:
    df_colostrum = df_colostrum.append(i, ignore_index = True)
    
df_colostrum.shape

(1480, 18)

In [137]:
df_colostrum.to_csv('/Users/gemavidal/Box Sync/Vet/Projects and Papers/2020 YSM USAID Final Report/df_colostrum_all.csv')

In [138]:
# Cleaning the data after append

columns = ['colostrumwithin24hours', 'continuousaccesstodamfirst24hours', 'dam_ageparturition_years',
           'dam_bcs1to5', 'parity', 'reasonnocolostrumfedwithin24hours', 'timeofbirth']

for i in columns:
    df_colostrum[i].replace({'unknown':np.nan,
                             'unkown':np.nan,
                             'NR':np.nan,
                             'Not applicable':np.nan,
                             'do not know':np.nan}, inplace = True)

In [139]:
columns = ['colostrumfromstepmom','colostrumwithin24hours', 'continuousaccesstodamfirst24hours', 
           'sex', 'timeofbirth']

for i in columns:
    df_colostrum[i].replace({'Yes':'yes',
                             'No':'no',
                             'Female':'female',
                             'Male':'male',
                             'Male ':'male',
                             'male ':'male',
                             'Day':'day',
                             'Night':'night',
                             'Night ':'night'}, inplace = True)

In [140]:
# Change the continous variables to floats

columns = ['dam_ageparturition_years', 'dam_bcs1to5', 'parity']

for i in columns:
    df_colostrum[i] = df_colostrum[i].astype(float)

In [141]:
# fix 'parity'
columns = ['parity']
for i in columns:
    df_colostrum[i].replace({0.0:1}, inplace = True)

In [142]:
# Cleaning dataframe

for i in df_colostrum:
    print (df_colostrum[i].value_counts())

Bovine      300
lamb         97
goat kid     44
Name: Species, dtype: int64
6.00     199
3.00     195
2.00     172
4.00     170
5.00     145
1.00     137
7.00     102
8.00      69
12.00     52
9.00      26
0.50      21
20.00     20
15.00     20
1.50      20
10.00     16
0.25      11
16.00     11
18.00      9
3.50       9
5.50       9
4.50       9
24.00      8
14.00      7
2.50       6
21.00      6
13.00      5
11.00      5
19.00      4
0.30       3
0.10       1
17.00      1
1.75       1
2.75       1
28.00      1
0.03       1
0.67       1
2.80       1
5.30       1
Name: age, dtype: int64
months    906
weeks     314
days      256
Name: age_units, dtype: int64
Suckling        229
Hand feeding     54
Name: colostrumfeeding, dtype: int64
no     256
yes     24
Name: colostrumfromstepmom, dtype: int64
yes    1348
no       45
Name: colostrumwithin24hours, dtype: int64
yes    1317
no       80
Name: continuousaccesstodamfirst24hours, dtype: int64
7.0     199
8.0     185
4.0     160
6.0     159
5.0     153
9.0      86
10.0     61
3.0      37
12.0     23
11.0     13
13.0     10
14.0      6
15.0      5
16.0      3
2.0       3
3.5       3
5.5       2
1.0       2
2.5       2
2.7       1
20.0      1
9.5       1
4.8       1
2.8       1
2.9       1
Name: dam_ageparturition_years, dtype: int64
3.0    590
2.0    329
4.0    145
1.0     61
5.0      4
Name: dam_bcs1to5, dtype: int64
Gondar     564
Dalocha    358
Awash      287
Amibara    154
Sululta    117
Name: district, dtype: int64
2.0     305
3.0     304
1.0     239
4.0     187
5.0      75
6.0      43
7.0      15
8.0      15
9.0      13
10.0      6
11.0      2
12.0      2
14.0      1
15.0      1
Name: parity, dtype: int64
0.0                                74
1.0                                67
Calf alert but unable to suck       8
Other                               5
Dam mismothering and weak calve     1
Name: reasonnocolostrumfedwithin24hours, dtype: int64
male      740
female    726
Name: sex, dtype: int64
day      682
night    474
Name: timeofbirth, dtype: int64
1hr      8
4hr      1
7hr      1
2hr      1
6hr      1
30min    1
3hr      1
Name: timeofcolostrumsucking, dtype: int64
1hr      46
2hr      24
5hr       6
3hr       5
6hr       2
3min      1
7hr       1
30min     1
Name: timeofcolostrumsucking_Addisu, dtype: int64
Before an hour    282
2-6 hours          93
7-12 hours          8
Name: timeto_firstcolostrum, dtype: int64
> 6    43
< 6    40
Name: timetofirstcolostrum_hrs_Chalachew, dtype: int64

In [143]:
# fix 'dam_ageparturition_years'
columns = ['dam_ageparturition_years']
for i in columns:
    df_colostrum[i].replace({3.5 : 3,
                             5.5 : 5,
                             2.5 : 2,
                             2.7 : 2,
                             9.5 : 9,
                             4.8 : 4,
                             2.8 : 2,
                             2.9 : 2}, inplace = True)

In [144]:
# Create a column for the production system
def prod_system (row):
    if (row['district'] == 'Gondar'):
        return 'Peri-urban'
    if (row['district'] == 'Sululta'):
        return 'Peri-urban'
    if (row['district'] == 'Dalocha'):
        return 'Mixed-crop'
    if (row['district'] == 'Awash'):
        return 'Pastoral'
    if (row['district'] == 'Amibara'):
        return 'Pastoral'

In [145]:
df_colostrum['prod_system'] = df_colostrum.apply(lambda row: prod_system(row), axis = 1)

In [146]:
# Change all the ages into weeks as units
def label_ageweeks (row):
    if (row['age_units'] == 'weeks'):
        return row['age']
    if (row['age_units'] == 'months'):
        return row['age'] * 4
    if (row['age_units'] == 'days' and row['age'] >= 5.0 and row['age'] <=9):
        return 1
    if (row['age_units'] == 'days' and row['age'] < 5.0):
        return 0.5
    if (row['age_units'] == 'days' and row['age'] > 9.0):
        return row['age'] / 7 #because all the ages given the condition fit in there

In [147]:
df_colostrum['age_weeks'] = df_colostrum.apply(lambda row: label_ageweeks(row), axis = 1)

In [148]:
for i in df_colostrum:
    print (df_colostrum[i].value_counts())

Bovine      300
lamb         97
goat kid     44
Name: Species, dtype: int64
6.00     199
3.00     195
2.00     172
4.00     170
5.00     145
1.00     137
7.00     102
8.00      69
12.00     52
9.00      26
0.50      21
20.00     20
15.00     20
1.50      20
10.00     16
0.25      11
16.00     11
18.00      9
3.50       9
5.50       9
4.50       9
24.00      8
14.00      7
2.50       6
21.00      6
13.00      5
11.00      5
19.00      4
0.30       3
0.10       1
17.00      1
1.75       1
2.75       1
28.00      1
0.03       1
0.67       1
2.80       1
5.30       1
Name: age, dtype: int64
months    906
weeks     314
days      256
Name: age_units, dtype: int64
Suckling        229
Hand feeding     54
Name: colostrumfeeding, dtype: int64
no     256
yes     24
Name: colostrumfromstepmom, dtype: int64
yes    1348
no       45
Name: colostrumwithin24hours, dtype: int64
yes    1317
no       80
Name: continuousaccesstodamfirst24hours, dtype: int64
7.0     199
8.0     185
4.0     161
6.0     159
5.0     155
9.0      87
10.0     61
3.0      40
12.0     23
11.0     13
13.0     10
2.0       8
14.0      6
15.0      5
16.0      3
1.0       2
20.0      1
Name: dam_ageparturition_years, dtype: int64
3.0    590
2.0    329
4.0    145
1.0     61
5.0      4
Name: dam_bcs1to5, dtype: int64
Gondar     564
Dalocha    358
Awash      287
Amibara    154
Sululta    117
Name: district, dtype: int64
2.0     305
3.0     304
1.0     239
4.0     187
5.0      75
6.0      43
7.0      15
8.0      15
9.0      13
10.0      6
11.0      2
12.0      2
14.0      1
15.0      1
Name: parity, dtype: int64
0.0                                74
1.0                                67
Calf alert but unable to suck       8
Other                               5
Dam mismothering and weak calve     1
Name: reasonnocolostrumfedwithin24hours, dtype: int64
male      740
female    726
Name: sex, dtype: int64
day      682
night    474
Name: timeofbirth, dtype: int64
1hr      8
4hr      1
7hr      1
2hr      1
6hr      1
30min    1
3hr      1
Name: timeofcolostrumsucking, dtype: int64
1hr      46
2hr      24
5hr       6
3hr       5
6hr       2
3min      1
7hr       1
30min     1
Name: timeofcolostrumsucking_Addisu, dtype: int64
Before an hour    282
2-6 hours          93
7-12 hours          8
Name: timeto_firstcolostrum, dtype: int64
> 6    43
< 6    40
Name: timetofirstcolostrum_hrs_Chalachew, dtype: int64
Peri-urban    681
Pastoral      441
Mixed-crop    358
Name: prod_system, dtype: int64
24.000000    160
8.000000     158
1.000000     157
12.000000    149
4.000000     136
16.000000    122
0.500000      99
20.000000     98
2.000000      56
6.000000      45
48.000000     32
3.000000      31
32.000000     31
5.000000      21
10.000000     19
9.000000      19
7.000000      18
28.000000     16
2.142857      14
14.000000     10
18.000000     10
22.000000      9
2.857143       9
72.000000      8
36.000000      7
15.000000      5
13.000000      5
96.000000      4
11.000000      4
19.000000      4
1.200000       3
44.000000      2
1.428571       2
0.400000       1
11.200000      1
0.120000       1
2.680000       1
21.200000      1
40.000000      1
2.285714       1
80.000000      1
1.500000       1
60.000000      1
17.000000      1
56.000000      1
Name: age_weeks, dtype: int64

In [149]:
df_colostrum.loc[(df_colostrum['age_weeks'] < 1.0)&(df_colostrum['age_units']=='days')][['age', 'age_units', 'age_weeks']]

      age age_units  age_weeks
5     3.0      days        0.5
14    3.0      days        0.5
21    4.0      days        0.5
23    4.0      days        0.5
1062  4.0      days        0.5
1079  4.0      days        0.5
1161  3.0      days        0.5
1163  2.0      days        0.5
1185  1.0      days        0.5
1186  3.0      days        0.5
1187  2.0      days        0.5
1188  2.0      days        0.5
1189  4.0      days        0.5
1194  4.0      days        0.5
1197  3.0      days        0.5
1198  2.0      days        0.5
1199  4.0      days        0.5
1203  3.0      days        0.5
1222  3.0      days        0.5
1223  1.0      days        0.5
1229  1.0      days        0.5
1231  2.0      days        0.5
1232  1.0      days        0.5
1243  4.0      days        0.5
1244  1.0      days        0.5
1251  1.0      days        0.5
1252  3.0      days        0.5
1253  3.0      days        0.5
1255  4.0      days        0.5
1256  1.0      days        0.5
...   ...       ...        ...
1387  3.0      days        0.5
1388  3.0      days        0.5
1389  2.0      days        0.5
1391  2.0      days        0.5
1392  3.0      days        0.5
1396  4.0      days        0.5
1402  3.0      days        0.5
1403  3.0      days        0.5
1404  2.0      days        0.5
1406  4.0      days        0.5
1418  3.0      days        0.5
1419  3.0      days        0.5
1420  4.0      days        0.5
1421  4.0      days        0.5
1426  2.0      days        0.5
1427  3.0      days        0.5
1431  4.0      days        0.5
1437  3.0      days        0.5
1439  4.0      days        0.5
1442  3.0      days        0.5
1444  3.0      days        0.5
1445  3.0      days        0.5
1446  4.0      days        0.5
1447  4.0      days        0.5
1457  4.0      days        0.5
1459  3.0      days        0.5
1460  2.0      days        0.5
1469  2.0      days        0.5
1470  2.0      days        0.5
1471  2.0      days        0.5

[94 rows x 3 columns]

In [150]:
# Fix variables 'timeofcolostrumsucking' and 'timeofcolostrumsucking_Addisu'

df_colostrum.loc[(df_colostrum['timeofcolostrumsucking_Addisu'].notnull())&
                 (df_colostrum['timeofcolostrumsucking'].notnull())][['timeofcolostrumsucking','timeofcolostrumsucking_Addisu']]

Empty DataFrame
Columns: [timeofcolostrumsucking, timeofcolostrumsucking_Addisu]
Index: []

In [151]:
df_colostrum.to_csv('/Users/gemavidal/Box Sync/Vet/Projects and Papers/2020 YSM USAID Final Report/df_colostrum_cleaned.csv')